name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_linux:
    runs-on: ubuntu-latest    
    steps:
    - name: Install Postgresql 11 and PostGIS
      uses: huaxk/postgis-action@v1
      with:
        postgresql version: '11'
        postgresql password: 'password'
        postgresql user: 'hastile' 
        postgresql db: 'hastile_test'

    - name: Get code
      uses: actions/checkout@v2
      with:
        path: ./hastile

    - name: Checkout zellige repo
      uses: actions/checkout@v2
      with:
        repository: zellige/zellige
        path: ./zellige
    
    - name: Cache Stack downloads
      uses: actions/cache@v1
      env:
        cache-name: stack-download
      with:
        path: /home/runner/.stack/
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

    - name: Cache Stack Build
      uses: actions/cache@v1
      env:
        cache-name: stack-work
      with:
        path: .stack-work/
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/hastile.cabal') }}${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}-
    
    - name: stack pre (setup, configure)
      run: |
        stack setup --stack-yaml stack-ci.yaml --no-terminal -j2
        stack build --stack-yaml stack-ci.yaml --no-system-ghc --only-configure --no-terminal -j2

    - name: stack compile and install
      run: |
        stack build  --stack-yaml stack-ci.yaml --no-terminal -j2
        stack install  --stack-yaml stack-ci.yaml --no-terminal -j2

    - name: db migrate
      run: |
        ./db/migration setup --stack test
      working-directory: ./hastile
    
    - name: stack test
      run: |
        stack test  --stack-yaml stack-ci.yaml --no-terminal -j2

    - name: create zip
      run: |
        stack install --stack-yaml stack-ci.yaml --local-bin-path .
        zip -r hastile-linux.zip ./hastile

    - name: Upload zip of binary
      uses: actions/upload-artifact@v1
      with:
        name: hastile-linux
        path: hastile-linux.zip
  
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Install Postgresql 11 Client
      run: |
        choco install postgresql11
        echo "::add-path::C:\Program Files\PostgreSQL\11\bin"

    - name: Get code
      uses: actions/checkout@v2
    
    - name: Cache Stack downloads
      uses: actions/cache@v1
      env:
        cache-name: stack-download
      with:
        path: C:\Users\runneradmin\AppData\Roaming\stack
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

    - name: Cache Stack Build
      uses: actions/cache@v1
      env:
        cache-name: stack-work
      with:
        path: .stack-work/
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/evie.cabal') }}${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}-
      
    - name: stack pre (setup, configure)
      run: |
        echo "::add-path::C:\Program Files\PostgreSQL\11\bin"
        stack setup --stack-yaml stack-ci.yaml --no-terminal -j2
        stack build --stack-yaml stack-ci.yaml --no-system-ghc --only-configure --no-terminal -j2

    - name: stack compile
      run: |
        echo "::add-path::C:\Program Files\PostgreSQL\11\bin"
        stack build --stack-yaml stack-ci.yaml --no-terminal -j2

    - name: create zip
      shell: powershell -Command "& '{0}'"
      run: |
        echo "::add-path::C:\Program Files\PostgreSQL\11\bin"
        stack install --stack-yaml stack-ci.yaml --local-bin-path .
        7z a hastile-windows.zip ./hastile.exe

    - name: Upload zip of binary
      uses: actions/upload-artifact@v1
      with:
        name: hastile-windows
        path: hastile-windows.zip
  
  build_macos:
    runs-on: macos-latest
    steps:
    - name: Install Postgresql 11 Client
      run: |
        brew install postgresql@11

    - name: Get code
      uses: actions/checkout@v2
    
    - name: Cache Stack downloads
      uses: actions/cache@v1
      env:
        cache-name: stack-download
      with:
        path: /Users/runner/.stack/
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

    - name: Cache Stack Build
      uses: actions/cache@v1
      env:
        cache-name: stack-work
      with:
        path: .stack-work/
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/evie.cabal') }}${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}-
      
    - name: stack pre (setup, configure)
      timeout-minutes: 720
      run: |
        export PATH=/usr/local/opt/postgresql@11/bin:$PATH
        export LDFLAGS="-L/usr/local/opt/postgresql@11/lib"
        export CPPFLAGS="-I/usr/local/opt/postgresql@11/include"
        stack setup --stack-yaml stack-ci.yaml --no-terminal
        stack build --stack-yaml stack-ci.yaml --no-system-ghc --only-configure --no-terminal

    - name: stack compile
      timeout-minutes: 720
      run: |
        export PATH=/usr/local/opt/postgresql@11/bin:$PATH
        export LDFLAGS="-L/usr/local/opt/postgresql@11/lib"
        export CPPFLAGS="-I/usr/local/opt/postgresql@11/include"
        stack build --stack-yaml stack-ci.yaml --no-terminal

    - name: create zip
      run: |
        export PATH=/usr/local/opt/postgresql@11/bin:$PATH
        export LDFLAGS="-L/usr/local/opt/postgresql@11/lib"
        export CPPFLAGS="-I/usr/local/opt/postgresql@11/include"
        stack install --stack-yaml stack-ci.yaml --local-bin-path .
        zip -r hastile-macos.zip ./hastile

    - name: Upload zip of binary
      uses: actions/upload-artifact@v1
      with:
        name: hastile-macos
        path: hastile-macos.zip

  release:
    runs-on: ubuntu-latest    
    needs: [build_linux, build_windows, build_macos]
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: hastile-linux

    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: hastile-windows

    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: hastile-macos

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## ‚ú® Features
          * Nothing this time, but please raise an issue if you would like a particular feature.

          ## üçè Improvements
          * Raise an issue if something could be improved.

          ## üêû Bug Fixes
          * Bugs, what bugs? Please raise an issue if you find anything that doesn't work as expected.
        draft: true
        prerelease: false

    - name: Upload Release Assets
      id: upload-release-assets
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workflow }}-CHANGELOG.txt
        files: |
         ./hastile/hastile-linux.zip
         ./hastile/hastile-windows.zip
         ./hastile/hastile-macos.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
